# Generated by Django 4.1.3 on 2022-11-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_recipe_recipebox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipebox',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
